spring.application.name=educonnect-backend

spring.mongodb.uri=mongodb+srv://nkneya04_db_user:2gl1ZiDjaJ482yhN@educonnectcluster.pk6bpzg.mongodb.net/educonnect?retryWrites=true&w=majority&appName=EduConnectCluster

server.port=8080